//SELECT D.NAME "부서명(NAME)"
//, AVG(E.AGE) "평균나이(AVGAGE)"
//FROM DEPT D
//, EMPLOYEE E
//WHERE 1 = 1
//AND D.CODE = E.DEPTCODE
//GROUP BY D.CODE, D.NAME
//HAVING AVG(E.AGE) > 30
//ORDER BY AVG(E.AGE) ASC
//;